export interface RegistryFile {
  /** Path to the source file, relative to packages/components. */
  source: string;
  /** Path where the CLI writes the file inside the consumer project, relative to its configured components root. */
  target: string;
}

/**
 * How settled a component's API is. A judgement the team makes, so it is
 * declared here rather than derived: nothing in the source says whether the
 * props are still moving.
 */
export type ComponentStatus = "stable" | "beta";

export interface ComponentDefinition {
  name: string;
  category: "utility" | "actions" | "forms" | "layout" | "feedback" | "overlays";
  description: string;
  /** Utility entries are never surfaced, so they carry no status. */
  status?: ComponentStatus;
  /** Names of other registry entries this component's source imports. */
  dependencies: string[];
  /** npm packages the copied source expects to be installed in the consumer project. */
  npmDependencies: string[];
  files: RegistryFile[];
  /**
   * Native HTML element whose attributes this component spreads onto its root.
   * Docs surfaces use it to tell readers that attributes inherited from React's
   * DOM typings (className, disabled, children, ...) are accepted even though
   * they are filtered out of the generated props table.
   */
  extendsElement?: string;
}

export const componentDefinitions: ComponentDefinition[] = [
  {
    name: "utils",
    category: "utility",
    description: "Shared classnames helper used by every component.",
    dependencies: [],
    npmDependencies: [],
    files: [{ source: "src/lib/cn.ts", target: "lib/cn.ts" }],
  },
  {
    name: "categorical-color",
    category: "utility",
    description:
      "Shared vocabulary of hue names for telling members of a set apart, with no status meaning.",
    dependencies: [],
    npmDependencies: [],
    files: [
      {
        source: "src/lib/categorical-color.ts",
        target: "lib/categorical-color.ts",
      },
    ],
  },
  {
    name: "icon",
    category: "utility",
    description: "Icon library and the component that renders it.",
    dependencies: [],
    npmDependencies: ["react"],
    files: [
      { source: "src/icons/paths.ts", target: "icons/paths.ts" },
      { source: "src/icon.tsx", target: "components/ui/icon.tsx" },
    ],
    extendsElement: "svg",
  },
  {
    name: "button",
    category: "actions",
    status: "stable",
    description: "Primary and secondary action button.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/button.tsx", target: "components/ui/button.tsx" }],
    extendsElement: "button",
  },
  {
    name: "input",
    category: "forms",
    status: "stable",
    description: "Labeled text input with error state.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/input.tsx", target: "components/ui/input.tsx" }],
    extendsElement: "input",
  },
  {
    name: "search-field",
    category: "forms",
    status: "stable",
    description: "Text input with a leading search icon, scoped to one screen's content — not the global NavbarSearch.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/search-field.tsx", target: "components/ui/search-field.tsx" }],
    extendsElement: "input",
  },
  {
    name: "card",
    category: "layout",
    status: "stable",
    description: "Composable container with header, body and footer.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/card.tsx", target: "components/ui/card.tsx" }],
    extendsElement: "div",
  },
  {
    name: "badge",
    category: "feedback",
    status: "stable",
    description: "Status label with color variants.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/badge.tsx", target: "components/ui/badge.tsx" }],
    extendsElement: "span",
  },
  {
    name: "tag",
    category: "feedback",
    status: "stable",
    description:
      "Categorical label whose color tells members of a set apart without implying a status.",
    dependencies: ["utils", "categorical-color"],
    npmDependencies: ["react"],
    files: [{ source: "src/tag.tsx", target: "components/ui/tag.tsx" }],
    extendsElement: "span",
  },
  {
    name: "select",
    category: "forms",
    status: "stable",
    description: "Accessible dropdown for 7 to 20 options, with an async loading state.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-select"],
    files: [{ source: "src/select.tsx", target: "components/ui/select.tsx" }],
  },
  {
    name: "combobox",
    category: "forms",
    status: "stable",
    description: "Searchable dropdown for more than 20 options, with single or multiple selection.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-popover", "cmdk"],
    files: [{ source: "src/combobox.tsx", target: "components/ui/combobox.tsx" }],
  },
  {
    name: "checkbox",
    category: "forms",
    status: "stable",
    description: "Labeled checkbox with checked, unchecked and indeterminate states.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/checkbox.tsx", target: "components/ui/checkbox.tsx" }],
  },
  {
    name: "radio-group",
    category: "forms",
    status: "stable",
    description: "Group of mutually exclusive options, one selection at a time.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/radio-group.tsx", target: "components/ui/radio-group.tsx" }],
  },
  {
    name: "switch",
    category: "forms",
    status: "stable",
    description: "Toggle for a setting that takes effect immediately.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-switch"],
    files: [{ source: "src/switch.tsx", target: "components/ui/switch.tsx" }],
  },
  {
    name: "table",
    category: "layout",
    status: "stable",
    description: "Static, composable table for tabular data: header, body, footer, rows and cells.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/table.tsx", target: "components/ui/table.tsx" }],
    extendsElement: "table",
  },
  {
    name: "pagination",
    category: "actions",
    status: "stable",
    description: "Page navigation: previous/next controls and numbered pages with ellipsis.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/pagination.tsx", target: "components/ui/pagination.tsx" }],
  },
  {
    name: "pagination-bar",
    category: "actions",
    status: "stable",
    description: "Result-range summary and a page-size selector alongside Pagination, composed without modifying it.",
    dependencies: ["utils", "icon", "pagination", "select"],
    npmDependencies: ["react"],
    files: [{ source: "src/pagination-bar.tsx", target: "components/ui/pagination-bar.tsx" }],
  },
  {
    name: "chip",
    category: "feedback",
    status: "stable",
    description:
      "A filter label: removable (an applied filter with its ×) or selectable (a toggle with an optional count).",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/chip.tsx", target: "components/ui/chip.tsx" }],
  },
  {
    name: "kbd",
    category: "feedback",
    status: "beta",
    description: "A key drawn as a key, to document a shortcut. Informative only.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/kbd.tsx", target: "components/ui/kbd.tsx" }],
    extendsElement: "kbd",
  },
  {
    name: "textarea",
    category: "forms",
    status: "beta",
    description: "The multi-line pair of Input: same label, hint, error and focus treatment.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/textarea.tsx", target: "components/ui/textarea.tsx" }],
    extendsElement: "textarea",
  },
  {
    name: "option-card",
    category: "forms",
    status: "beta",
    description:
      "Mutually exclusive options as cards, each with a description and content of its own — what RadioGroup cannot hold.",
    dependencies: ["utils", "kbd"],
    npmDependencies: ["react"],
    files: [{ source: "src/option-card.tsx", target: "components/ui/option-card.tsx" }],
  },
  {
    name: "segmented-control",
    category: "forms",
    status: "stable",
    description: "Mutually exclusive options shown as contiguous segments.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [
      { source: "src/segmented-control.tsx", target: "components/ui/segmented-control.tsx" },
    ],
  },
  {
    name: "tabs",
    category: "layout",
    status: "stable",
    description: "Switch between mutually exclusive sections without leaving the page.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-tabs"],
    files: [{ source: "src/tabs.tsx", target: "components/ui/tabs.tsx" }],
  },
  {
    name: "slider",
    category: "forms",
    status: "stable",
    description:
      "Set one or more values along a range; several thumbs partition it into labelled spans.",
    dependencies: ["utils", "categorical-color"],
    npmDependencies: ["react", "@radix-ui/react-slider"],
    files: [{ source: "src/slider.tsx", target: "components/ui/slider.tsx" }],
  },
  {
    name: "accordion",
    category: "layout",
    status: "stable",
    description: "In-page disclosure of sections, composed from Accordion, AccordionItem, AccordionTrigger and AccordionContent.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-accordion"],
    files: [{ source: "src/accordion.tsx", target: "components/ui/accordion.tsx" }],
  },
  {
    name: "alert",
    category: "feedback",
    status: "stable",
    description: "In-flow message with a severity icon, optional title and optional action.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/alert.tsx", target: "components/ui/alert.tsx" }],
    extendsElement: "div",
  },
  {
    name: "avatar",
    category: "feedback",
    status: "stable",
    description:
      "Initials on a neutral fill or an assigned categorical color, with an overlapping group and overflow count.",
    dependencies: ["utils", "categorical-color"],
    npmDependencies: ["react"],
    files: [{ source: "src/avatar.tsx", target: "components/ui/avatar.tsx" }],
  },
  {
    name: "progress",
    category: "feedback",
    status: "stable",
    description: "Single-value progress bar and a proportional segmented bar.",
    dependencies: ["utils", "severity"],
    npmDependencies: ["react"],
    files: [{ source: "src/progress.tsx", target: "components/ui/progress.tsx" }],
  },
  {
    name: "severity",
    category: "utility",
    description:
      "Status severity of a 0–100 percentage with an optional early-warning band, shared by every bar that reads a percentage.",
    dependencies: [],
    npmDependencies: [],
    files: [{ source: "src/lib/severity.ts", target: "lib/severity.ts" }],
  },
  {
    name: "meter",
    category: "feedback",
    status: "beta",
    description: "A Progress with its percentage written beside it, for a table row.",
    dependencies: ["utils", "progress"],
    npmDependencies: ["react"],
    files: [{ source: "src/meter.tsx", target: "components/ui/meter.tsx" }],
    extendsElement: "div",
  },
  {
    name: "capacity-bar",
    category: "feedback",
    status: "beta",
    description:
      "Allocated against available: the figures, the occupancy coloured by severity, and a stacked bar whose empty track is the room left.",
    dependencies: ["utils", "accent-tone", "severity", "progress"],
    npmDependencies: ["react"],
    files: [{ source: "src/capacity-bar.tsx", target: "components/ui/capacity-bar.tsx" }],
    extendsElement: "div",
  },
  {
    name: "distribution-card",
    category: "feedback",
    status: "beta",
    description:
      "Summary card for a distribution: rubric, total, segmented bar, two-column legend and an optional footer reading.",
    dependencies: ["utils", "card", "progress"],
    npmDependencies: ["react"],
    files: [{ source: "src/distribution-card.tsx", target: "components/ui/distribution-card.tsx" }],
    extendsElement: "div",
  },
  {
    name: "sparkline",
    category: "feedback",
    status: "beta",
    description:
      "A short series as vertical bars — the shape behind a figure a summary card already states.",
    dependencies: ["utils", "accent-tone"],
    npmDependencies: ["react"],
    files: [{ source: "src/sparkline.tsx", target: "components/ui/sparkline.tsx" }],
    extendsElement: "div",
  },
  {
    name: "accent-tone",
    category: "utility",
    description:
      "Shared vocabulary of ordered hue names for the steps of an ordinal scale, with no status meaning.",
    dependencies: [],
    npmDependencies: [],
    files: [{ source: "src/lib/accent-tone.ts", target: "lib/accent-tone.ts" }],
  },
  {
    name: "level-meter",
    category: "feedback",
    status: "beta",
    description:
      "Equal-width segments filled up to a position, for a closed ordinal scale — not a proportional bar.",
    dependencies: ["utils", "accent-tone"],
    npmDependencies: ["react"],
    files: [{ source: "src/level-meter.tsx", target: "components/ui/level-meter.tsx" }],
    extendsElement: "div",
  },
  {
    name: "seniority-card",
    category: "feedback",
    status: "beta",
    description:
      "A person's seniority level as a fixed-size block with its label and a four-step tinted meter. Draws no surface of its own.",
    dependencies: ["utils", "accent-tone", "level-meter"],
    npmDependencies: ["react"],
    files: [{ source: "src/seniority-card.tsx", target: "components/ui/seniority-card.tsx" }],
    extendsElement: "div",
  },
  {
    name: "breadcrumb",
    category: "layout",
    status: "stable",
    description: "Current-page navigation path, collapsing to an ellipsis beyond three levels.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/breadcrumb.tsx", target: "components/ui/breadcrumb.tsx" }],
  },
  {
    name: "link",
    // Misma categoría que breadcrumb: el catálogo no tiene una familia propia
    // de navegación, y abrir una para un solo componente dejaría a breadcrumb,
    // navbar y sidebar del otro lado.
    category: "layout",
    status: "beta",
    description: "Text hyperlink with a parameterizable tone, brand or neutral.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-slot"],
    files: [{ source: "src/link.tsx", target: "components/ui/link.tsx" }],
    extendsElement: "a",
  },
  {
    name: "date-calendar",
    category: "utility",
    description: "Shared calendar styling and ISO date helpers used by DateField and DateRangeField.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "react-day-picker"],
    files: [{ source: "src/date-calendar.tsx", target: "components/ui/date-calendar.tsx" }],
  },
  {
    name: "date-field",
    category: "forms",
    status: "stable",
    description: "Single date field captured as ISO text, with a calendar dropdown as an optional aid.",
    dependencies: ["utils", "icon", "date-calendar"],
    npmDependencies: ["react", "@radix-ui/react-popover", "react-day-picker", "date-fns"],
    files: [{ source: "src/date-field.tsx", target: "components/ui/date-field.tsx" }],
  },
  {
    name: "date-range-field",
    category: "forms",
    status: "stable",
    description: "Two-date range field captured as ISO text, with an abbreviated read format and a shared calendar dropdown.",
    dependencies: ["utils", "icon", "date-calendar"],
    npmDependencies: ["react", "@radix-ui/react-popover", "react-day-picker", "date-fns"],
    files: [{ source: "src/date-range-field.tsx", target: "components/ui/date-range-field.tsx" }],
  },
  {
    name: "empty-state",
    category: "feedback",
    status: "stable",
    description: "Centered icon, title, description and action for a list or section with nothing to show.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/empty-state.tsx", target: "components/ui/empty-state.tsx" }],
    extendsElement: "div",
  },
  {
    name: "skeleton",
    category: "feedback",
    status: "stable",
    description: "Single pulsing placeholder block, sized and shaped via className to imitate the real content.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/skeleton.tsx", target: "components/ui/skeleton.tsx" }],
    extendsElement: "div",
  },
  {
    name: "toast",
    category: "feedback",
    status: "stable",
    description: "Provider and hook to queue a single, auto-dismissing confirmation, anchored bottom-right.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-toast"],
    files: [{ source: "src/toast.tsx", target: "components/ui/toast.tsx" }],
  },
  {
    name: "tooltip",
    category: "overlays",
    status: "stable",
    description: "Short phrase shown after a delay on hover or focus, self-contained with no provider to mount.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-tooltip"],
    files: [{ source: "src/tooltip.tsx", target: "components/ui/tooltip.tsx" }],
  },
  {
    name: "popover",
    category: "overlays",
    status: "stable",
    description: "Anchored surface of arbitrary content, composed from Popover, PopoverTrigger, PopoverAnchor and PopoverContent.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-popover"],
    files: [{ source: "src/popover.tsx", target: "components/ui/popover.tsx" }],
  },
  {
    name: "filter-button",
    category: "forms",
    status: "stable",
    description: "Button that opens a checklist of options, e.g. \"Seniority\" above a Table, showing an active count when any are checked.",
    dependencies: ["utils", "icon", "checkbox", "popover"],
    npmDependencies: ["react"],
    files: [{ source: "src/filter-button.tsx", target: "components/ui/filter-button.tsx" }],
  },
  {
    name: "command-palette",
    category: "overlays",
    status: "stable",
    description: "Global ⌘K overlay with a filtered command list, composed from CommandPalette and its parts.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-dialog", "cmdk"],
    files: [{ source: "src/command-palette.tsx", target: "components/ui/command-palette.tsx" }],
  },
  {
    name: "menu",
    category: "overlays",
    status: "stable",
    description: "Anchored dropdown of actionable items, composed from Menu, MenuItem and MenuSeparator.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-dropdown-menu"],
    files: [{ source: "src/menu.tsx", target: "components/ui/menu.tsx" }],
  },
  {
    name: "modal",
    category: "overlays",
    status: "stable",
    description: "Centered, blocking overlay for a decision — confirm, short form. Never nests another Modal.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-dialog"],
    files: [{ source: "src/modal.tsx", target: "components/ui/modal.tsx" }],
  },
  {
    name: "drawer",
    category: "overlays",
    status: "stable",
    description: "Panel that slides in from the edge to show detail without losing the table or list behind it.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react", "@radix-ui/react-dialog"],
    files: [{ source: "src/drawer.tsx", target: "components/ui/drawer.tsx" }],
  },
  {
    name: "activity-timeline",
    category: "feedback",
    status: "stable",
    description: "Ordered audit trail — who did what and when, composed from ActivityTimeline and ActivityTimelineItem.",
    dependencies: ["utils"],
    npmDependencies: ["react"],
    files: [{ source: "src/activity-timeline.tsx", target: "components/ui/activity-timeline.tsx" }],
  },
  {
    name: "stepper",
    category: "layout",
    status: "stable",
    description: "Horizontal step indicator for multi-step flows, composed from Stepper and StepperStep.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/stepper.tsx", target: "components/ui/stepper.tsx" }],
  },
  {
    name: "notification-menu",
    category: "overlays",
    status: "stable",
    description: "Anchored panel for actionable notifications, composed from NotificationMenu, NotificationMenuHeader, NotificationMenuList, NotificationMenuItem and NotificationMenuFooter.",
    dependencies: ["utils"],
    npmDependencies: ["react", "@radix-ui/react-dropdown-menu"],
    files: [{ source: "src/notification-menu.tsx", target: "components/ui/notification-menu.tsx" }],
  },
  {
    name: "file-input",
    category: "forms",
    status: "stable",
    description: "Single-file field with drag-and-drop over a real file input, so a keyboard alternative always exists.",
    dependencies: ["utils", "icon"],
    npmDependencies: ["react"],
    files: [{ source: "src/file-input.tsx", target: "components/ui/file-input.tsx" }],
  },
  {
    name: "file-uploader",
    category: "forms",
    status: "stable",
    description: "Multi-file drag-and-drop field with a per-row status the consumer controls — uploading, success or error.",
    dependencies: ["utils", "icon", "progress"],
    npmDependencies: ["react"],
    files: [{ source: "src/file-uploader.tsx", target: "components/ui/file-uploader.tsx" }],
  },
  {
    name: "navbar",
    category: "layout",
    status: "stable",
    description: "The one top bar every product shares — brand and app switcher, global search, utilities, notifications and account, composed from Menu and NotificationMenu.",
    dependencies: ["utils", "icon", "avatar", "menu", "notification-menu"],
    npmDependencies: ["react", "@radix-ui/react-dropdown-menu"],
    files: [{ source: "src/navbar.tsx", target: "components/ui/navbar.tsx" }],
  },
  {
    name: "sidebar",
    category: "layout",
    status: "stable",
    description: "Single-level, grouped side navigation with a persistent collapsed state, an active item marked by three signals at once, and counters reserved for pending work.",
    dependencies: ["utils", "icon", "tooltip"],
    npmDependencies: ["react"],
    files: [{ source: "src/sidebar.tsx", target: "components/ui/sidebar.tsx" }],
  },
  {
    name: "app-shell",
    category: "layout",
    status: "beta",
    description:
      "The Navbar + Sidebar fusion: full-height side navigation with the brand in its header, the bar beside it with a hamburger that collapses it, and the app's content as children.",
    dependencies: ["utils", "icon", "sidebar", "navbar"],
    npmDependencies: ["react"],
    files: [{ source: "src/app-shell.tsx", target: "components/ui/app-shell.tsx" }],
    extendsElement: "div",
  },
];
