import type { PersonDetail } from "../../../adapters/PersonDetailAdapter";
import type { PersonDto } from "../../../services/personService";

const person: PersonDto = {
  id: "p1",
  name: "María González",
  documentId: "1036884001",
  entraObjectId: "",
  userPrincipalName: "maria.gonzalez@tuya.com",
  position: "Backend Dev",
  role: "Contributor",
  technicalLeadId: null,
  technicalLeadName: null,
  technicalLeadOfCount: 0,
  level: 3,
  levelLabel: "Avanzado",

  seniority: "Intermediate",
  seniorityLabel: "Intermedio",
  modality: "Hybrid",
  availableFte: 1,
  utilization: 80,
  stacks: [],
  monthlyCost: 7_900_000,
  startDate: "2023-05-15",
  chapterId: null,
  providerId: null,
  createdAtUtc: "",
  updatedAtUtc: null,
};

/** María: con célula, identidad DevOps vinculada, bus factor 1. */
export const assigned: PersonDetail = {
  person,
  initials: "MG",
  level: 3,
  modalityLabel: "Híbrido",
  isExternal: false,
  providerName: null,
  contractEndsAt: null,
  // Dos responsables distintos a propósito: el del chapter es quien la tiene
  // a cargo, el de la línea es otra cosa. Con el mismo nombre en los dos, una
  // prueba que buscara "· Lead: X" no distinguiría cuál de las dos filas lo
  // muestra.
  chapterName: "Core y Datos",
  chapterLeadName: "Tomás Giraldo",
  expertiseLineName: "Backend",
  expertiseLineLeadName: "Esteban Licona",
  startDateLabel: "15 may 2023",
  tenureLabel: "3 años y 3 meses",
  allocation: {
    id: "a1",
    squadId: "s1",
    squadName: "Backend Platform",
    squadCriticality: "High",
    squadTribe: "Ecosistema Digital",
    squadDescription: "",
    teammates: ["Carlos López", "Andrés Martínez"],
    dedicationPercentage: 80,
    bauPercentage: 50,
    transformationPercentage: 30,
    since: "2024-03-12",
    requiredLevel: 3,
    criticalityLabel: "Alta",
    freePercentage: 20,
    freeFte: 0.2,
    sinceLabel: "12 mar 2024",
    levelGap: "Adequate",
  },
  assignedFte: 0.8,
  devOpsIdentity: {
    id: "i1",
    userName: "mgonzalez@tuya",
    linkedAt: "2026-07-25",
    // 28 SP contra sus 22 habituales, con 0.80 FTE disponible de 1.0: dos
    // evidencias concurrentes hacia sobrecarga ya son una señal accionable.
    currentSprint: {
      sprint: {
        name: "S18",
        startDate: "2026-08-17",
        endDate: "2026-08-30",
        snapshotStatus: "Provisional",
        sealedAt: null,
      },
      committedPoints: 28,
      ownMedianPoints: 22,
      ownDeviationRate: 27.3,
      capacity: {
        contractualFte: 1,
        availableFte: 0.8,
        breakdown: {
          businessDays: 10,
          holidays: 1,
          vacationDays: 0,
          absenceDays: 1,
          otherUnavailableDays: 0,
        },
        availableHours: 64,
        deductedHours: 16,
      },
      signal: "PossibleOverload",
      notEvaluableReason: null,
      evidenceCount: 2,
    },
  },
  stacks: [
    {
      name: ".NET",
      level: 3,
      isPrimary: true,
      otherCoverers: 6,
      coverers: [
        { id: "p2", name: "Carlos López" },
        { id: "p3", name: "Daniela Castaño" },
      ],
      busFactorOne: false,
      levelLabel: "Avanzado",
    },
    {
      name: "AS400",
      level: 2,
      isPrimary: false,
      otherCoverers: 0,
      coverers: [],
      busFactorOne: true,
      levelLabel: "Competente",
    },
  ],
  primaryStackName: ".NET",
  sprintPointer: {
    kind: "sprint",
    balance: {
      signal: "PossibleOverload",
      overCount: 2,
      underCount: 0,
      squadContext: "NoSquad",
      notEvaluableReason: null,
      evidences: [],
    },
    meta: "2 de 6 señales · S18 · en curso",
  },
  costReading: "InRange",
  costReadingLabel: "en rango para Avanzado",
  suggestedSquads: [],
};

/** Camila: externa, sin célula, sin identidad DevOps, con sugerencias. */
export const unassigned: PersonDetail = {
  ...assigned,
  person: {
    ...person,
    id: "p2",
    name: "Camila Restrepo",
    userPrincipalName: "camila.restrepo@tuya.com",
    position: "Product Owner",
    role: "Contributor",
    technicalLeadId: null,
    technicalLeadName: null,
    technicalLeadOfCount: 0,
    level: 4,
    levelLabel: "Experto",

    seniority: "Senior",
    seniorityLabel: "Senior",
    modality: "Remote",
    providerId: "c1",
    startDate: "2026-08-04",
  },
  initials: "CR",
  level: 4,
  modalityLabel: "Remoto",
  isExternal: true,
  providerName: "Globant",
  contractEndsAt: "2026-12-31",
  tenureLabel: "hace 18 días",
  startDateLabel: "04 ago 2026",
  allocation: null,
  assignedFte: 0,
  devOpsIdentity: null,
  stacks: [
    {
      name: "Power BI",
      level: 2,
      isPrimary: true,
      otherCoverers: 2,
      coverers: [{ id: "p4", name: "Paula Ramírez" }],
      busFactorOne: false,
      levelLabel: "Competente",
    },
  ],
  primaryStackName: "Power BI",
  sprintPointer: { kind: "unlinked", balance: null, meta: null },
  costReading: "High",
  costReadingLabel: "alto para Experto",
  suggestedSquads: [
    {
      id: "pagos",
      name: "Pagos Instantáneos",
      criticality: "Low",
      reason: "Sin equipo",
      requiredLevel: 3,
      allocatedFte: 0,
      teamAvailableFte: 0,
    },
  ],
};
