import type { PersonDetail } from "../../../adapters/PersonDetailAdapter";
import type { PersonDto } from "../../../services/personService";

const person: PersonDto = {
  id: "p1",
  name: "María González",
  documentId: "1036884001",
  entraObjectId: "",
  userPrincipalName: "maria.gonzalez@tuya.com",
  position: "Backend Dev",
  role: "Contributor",
  technicalLeadId: null,
  technicalLeadName: null,
  technicalLeadOfCount: 0,
  seniority: 3,
  seniorityLabel: "Avanzado",
  modality: "Hybrid",
  availableFte: 1,
  utilization: 80,
  stacks: [],
  monthlyCost: 7_900_000,
  startDate: "2023-05-15",
  chapterId: null,
  providerId: null,
  createdAtUtc: "",
  updatedAtUtc: null,
};

const sprint = (s: string, bau: number, ini: number, validated = true) => ({
  sprint: s,
  sprintHours: 80,
  bauHours: bau,
  initiativeHours: ini,
  freeHours: 80 - bau - ini,
  status: validated ? ("Validated" as const) : ("Submitted" as const),
  workedHours: bau + ini,
  validated,
});

/** María: con célula, reporte por validar, exceso, bus factor 1. */
export const assigned: PersonDetail = {
  person,
  initials: "MG",
  sfiaLevel: 3,
  modalityLabel: "Híbrido",
  isExternal: false,
  providerName: null,
  contractEndsAt: null,
  // Dos responsables distintos a propósito: el del chapter es quien la tiene
  // a cargo, el de la línea es otra cosa. Con el mismo nombre en los dos, una
  // prueba que buscara "· Lead: X" no distinguiría cuál de las dos filas lo
  // muestra.
  chapterName: "Core y Datos",
  chapterLeadName: "Tomás Giraldo",
  expertiseLineName: "Backend",
  expertiseLineLeadName: "Esteban Licona",
  startDateLabel: "15 may 2023",
  tenureLabel: "3 años y 3 meses",
  allocation: {
    id: "a1",
    squadId: "s1",
    squadName: "Backend Platform",
    squadCriticality: "High",
    squadTribe: "Ecosistema Digital",
    squadDescription: "",
    teammates: ["Carlos López", "Andrés Martínez"],
    dedicationPercentage: 80,
    bauPercentage: 50,
    transformationPercentage: 30,
    since: "2024-03-12",
    requiredSfia: 3,
    criticalityLabel: "Alta",
    freePercentage: 20,
    freeFte: 0.2,
    sinceLabel: "12 mar 2024",
    sfiaGap: "Adequate",
  },
  assignedFte: 0.8,
  realFte: 0.9,
  deltaPoints: 10,
  currentReport: {
    ...sprint("S16", 42, 32, false),
    toleranceMin: 76,
    toleranceMax: 84,
    submittedAt: "2026-08-08",
    closesAt: "2026-08-22",
  },
  hoursWithinTolerance: true,
  sprints: [
    sprint("S14", 40, 30),
    sprint("S15", 40, 32),
    sprint("S16", 42, 32, false),
  ],
  expectedHours: 64,
  overReportingStreak: 2,
  devOpsIdentity: {
    id: "i1",
    userName: "mgonzalez@tuya",
    linkedAt: "2026-07-25",
    activeItems: 11,
    initiativeItems: 7,
    bauItems: 4,
    pendingCuration: 2,
  },
  devOpsCandidates: [],
  stacks: [
    {
      name: ".NET",
      level: 3,
      isPrimary: true,
      otherCoverers: 6,
      coverers: [
        { id: "p2", name: "Carlos López" },
        { id: "p3", name: "Daniela Castaño" },
      ],
      busFactorOne: false,
      levelLabel: "Avanzado",
    },
    {
      name: "AS400",
      level: 2,
      isPrimary: false,
      otherCoverers: 0,
      coverers: [],
      busFactorOne: true,
      levelLabel: "Competente",
    },
  ],
  costReading: "InRange",
  costReadingLabel: "en rango para Avanzado",
  suggestedSquads: [],
};

/** Camila: externa, sin célula, sin identidad DevOps, con sugerencias. */
export const unassigned: PersonDetail = {
  ...assigned,
  person: {
    ...person,
    id: "p2",
    name: "Camila Restrepo",
    userPrincipalName: "camila.restrepo@tuya.com",
    position: "Product Owner",
    role: "Contributor",
    technicalLeadId: null,
    technicalLeadName: null,
    technicalLeadOfCount: 0,
    seniority: 4,
    seniorityLabel: "Experto",
    modality: "Remote",
    providerId: "c1",
    startDate: "2026-08-04",
  },
  initials: "CR",
  sfiaLevel: 4,
  modalityLabel: "Remoto",
  isExternal: true,
  providerName: "Globant",
  contractEndsAt: "2026-12-31",
  tenureLabel: "hace 18 días",
  startDateLabel: "04 ago 2026",
  allocation: null,
  assignedFte: 0,
  realFte: null,
  deltaPoints: null,
  currentReport: null,
  hoursWithinTolerance: null,
  sprints: [],
  expectedHours: 0,
  overReportingStreak: 0,
  devOpsIdentity: null,
  devOpsCandidates: [
    { id: "i9", userName: "crestrepo@tuya", displayName: "Camila Restrepo" },
  ],
  stacks: [
    {
      name: "Power BI",
      level: 2,
      isPrimary: true,
      otherCoverers: 2,
      coverers: [{ id: "p4", name: "Paula Ramírez" }],
      busFactorOne: false,
      levelLabel: "Competente",
    },
  ],
  costReading: "High",
  costReadingLabel: "alto para Experto",
  suggestedSquads: [
    {
      id: "pagos",
      name: "Pagos Instantáneos",
      criticality: "Low",
      reason: "Sin equipo",
      requiredSfia: 3,
      allocatedFte: 0,
      teamAvailableFte: 0,
    },
  ],
};
