// <auto-generated />
using System;
using GestionCapacidad.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionCapacidad.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260905072300_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("EndsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("StartsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Absences", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Absences");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BauPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DedicationPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransformationPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SquadId");

                    b.HasIndex("PersonId", "SquadId")
                        .IsUnique();

                    b.ToTable("Allocations", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Allocations");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.BauTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadId", "Name")
                        .IsUnique();

                    b.ToTable("BauTasks", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "BauTasks");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.CapabilityMix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CapabilityMixes", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "CapabilityMixes");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Companies");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evaluation")
                        .HasColumnType("text")
                        .HasColumnName("Evaluation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadId", "Status");

                    b.ToTable("Initiatives", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Initiatives");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AvailableFte")
                        .HasColumnType("real");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("TechnicalLeadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("UserPrincipalName")
                        .IsUnique();

                    b.ToTable("People", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "People");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.QuestionPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QuestionPools", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "QuestionPools");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.SprintConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistoryWindowSprints")
                        .HasColumnType("integer");

                    b.Property<decimal>("HoursPerSprint")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MinHistorySprints")
                        .HasColumnType("integer");

                    b.Property<string>("SprintCloseTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("SprintsPerQuarter")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SprintConfigurations", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "SprintConfigurations");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("DevOpsBoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tribe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Squads", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Squads");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.TallaBandSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Boundaries")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TallaBandSets", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "TallaBandSets");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.CapabilityMix", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.CapabilityMixRow", "Rows", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CapabilityMixId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Capacidad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PorTalla")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CapabilityMixId");

                            b1.ToTable("CapabilityMixRows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CapabilityMixId");
                        });

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Person", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.PersonStack", "Stacks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonId");

                            b1.ToTable("PersonStacks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.QuestionPool", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.PoolQuestion", "Questions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Dimension")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Peso")
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<Guid>("QuestionPoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionPoolId");

                            b1.ToTable("PoolQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuestionPoolId");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.TallaBandSet", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.TallaBand", "Bands", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Lectura")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("PmMax")
                                .HasColumnType("decimal(6,2)");

                            b1.Property<decimal>("PmMin")
                                .HasColumnType("decimal(6,2)");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Talla")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<Guid>("TallaBandSetId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TallaBandSetId");

                            b1.ToTable("TallaBands", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TallaBandSetId");
                        });

                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
