// <auto-generated />
using System;
using GestionCapacidad.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionCapacidad.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906120849_AddExpertiseLineIdToPerson")]
    partial class AddExpertiseLineIdToPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("EndsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("StartsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Absences", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Absences");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BauPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DedicationPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransformationPercentage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SquadId");

                    b.HasIndex("PersonId", "SquadId")
                        .IsUnique();

                    b.ToTable("Allocations", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Allocations");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CatalogVersionAtClose")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Cycle");

                    b.ToTable("Assessments", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Assessments");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.BauTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadId", "Name")
                        .IsUnique();

                    b.ToTable("BauTasks", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "BauTasks");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.CapabilityMix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CapabilityMixes", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "CapabilityMixes");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Companies");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.ExpertiseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("ExpertiseLines", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "ExpertiseLines");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evaluation")
                        .HasColumnType("text")
                        .HasColumnName("Evaluation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SquadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadId", "Status");

                    b.ToTable("Initiatives", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Initiatives");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AvailableFte")
                        .HasColumnType("real");

                    b.Property<Guid?>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DevOpsUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ExpertiseLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("TechnicalLeadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ExpertiseLineId");

                    b.HasIndex("UserPrincipalName")
                        .IsUnique();

                    b.ToTable("People", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "People");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.PlanAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DueMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("FromLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PlanActions", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "PlanActions");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Prefacture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Prefactured")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SquadName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Period")
                        .IsUnique();

                    b.ToTable("Prefactures", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Prefactures");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.QuestionPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QuestionPools", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "QuestionPools");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Skills", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Skills");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.SkillCatalogVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SkillCatalogVersions", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "SkillCatalogVersions");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Holidays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sprints", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Sprints");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.SprintConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistoryWindowSprints")
                        .HasColumnType("integer");

                    b.Property<decimal>("HoursPerSprint")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("MinHistorySprints")
                        .HasColumnType("integer");

                    b.Property<string>("SprintCloseTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("SprintsPerQuarter")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Weeks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SprintConfigurations", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "SprintConfigurations");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.SprintSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AddedDuringSprintPoints")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CarryOverPoints")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CommittedAtStartPoints")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CompletedPoints")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OtherUnavailableDays")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SealedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Wip")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "SprintId")
                        .IsUnique();

                    b.ToTable("SprintSnapshots", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "SprintSnapshots");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Squad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("DevOpsBoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tribe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Squads", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "Squads");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.TallaBandSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Boundaries")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TallaBandSets", (string)null);

                    b.HasAnnotation("Mongo:CollectionName", "TallaBandSets");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Assessment", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.AssessmentSkillAnswer", "Skills", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("FrozenExpectedLevel")
                                .HasColumnType("integer");

                            b1.Property<string>("FrozenGroup")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("FrozenLevels")
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<string>("FrozenSkillName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int?>("Level")
                                .HasColumnType("integer");

                            b1.Property<string>("Met")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("AssessmentId");

                            b1.ToTable("AssessmentSkillAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.CapabilityMix", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.CapabilityMixRow", "Rows", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CapabilityMixId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Capacidad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("PorTalla")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CapabilityMixId");

                            b1.ToTable("CapabilityMixRows", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CapabilityMixId");
                        });

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Person", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.PersonStack", "Stacks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonId");

                            b1.ToTable("PersonStacks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Stacks");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Prefacture", b =>
                {
                    b.OwnsOne("GestionCapacidad.Domain.ValueObjects.AbsenceDiscount", "FrozenDiscount", b1 =>
                        {
                            b1.Property<Guid>("PrefactureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("FrozenDiscountAmount");

                            b1.Property<decimal>("BusinessDays")
                                .HasColumnType("numeric")
                                .HasColumnName("FrozenDiscountBusinessDays");

                            b1.HasKey("PrefactureId");

                            b1.ToTable("Prefactures");

                            b1.WithOwner()
                                .HasForeignKey("PrefactureId");
                        });

                    b.OwnsOne("GestionCapacidad.Domain.ValueObjects.BillingAdjustment", "Adjustment", b1 =>
                        {
                            b1.Property<Guid>("PrefactureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("AdjustmentAmount");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("AdjustmentNote");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("AdjustmentReason");

                            b1.HasKey("PrefactureId");

                            b1.ToTable("Prefactures");

                            b1.WithOwner()
                                .HasForeignKey("PrefactureId");
                        });

                    b.OwnsOne("GestionCapacidad.Domain.ValueObjects.Objection", "Objection", b1 =>
                        {
                            b1.Property<Guid>("PrefactureId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ObjectedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ObjectionObjectedAtUtc");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("ObjectionReason");

                            b1.HasKey("PrefactureId");

                            b1.ToTable("Prefactures");

                            b1.WithOwner()
                                .HasForeignKey("PrefactureId");
                        });

                    b.OwnsOne("GestionCapacidad.Domain.ValueObjects.PrefactureDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("PrefactureId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("DocumentAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("DocumentCurrency");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("DocumentNumber");

                            b1.Property<DateOnly>("ReceivedAt")
                                .HasColumnType("date")
                                .HasColumnName("DocumentReceivedAt");

                            b1.HasKey("PrefactureId");

                            b1.ToTable("Prefactures");

                            b1.WithOwner()
                                .HasForeignKey("PrefactureId");

                            b1.OwnsOne("GestionCapacidad.Domain.ValueObjects.Imputation", "Imputation", b2 =>
                                {
                                    b2.Property<Guid>("PrefactureDocumentPrefactureId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("AccountName")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("ImputationAccountName");

                                    b2.Property<string>("AccountNumber")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ImputationAccountNumber");

                                    b2.Property<string>("Concept")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("ImputationConcept");

                                    b2.Property<string>("CostCenter")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ImputationCostCenter");

                                    b2.Property<string>("CostObject")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("ImputationCostObject");

                                    b2.Property<string>("PaymentAccount")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("ImputationPaymentAccount");

                                    b2.Property<string>("PurchaseOrder")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ImputationPurchaseOrder");

                                    b2.HasKey("PrefactureDocumentPrefactureId");

                                    b2.ToTable("Prefactures");

                                    b2.WithOwner()
                                        .HasForeignKey("PrefactureDocumentPrefactureId");
                                });

                            b1.Navigation("Imputation")
                                .IsRequired();
                        });

                    b.Navigation("Adjustment");

                    b.Navigation("Document");

                    b.Navigation("FrozenDiscount");

                    b.Navigation("Objection");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.QuestionPool", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.PoolQuestion", "Questions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Dimension")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Peso")
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<Guid>("QuestionPoolId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionPoolId");

                            b1.ToTable("PoolQuestions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("QuestionPoolId");
                        });

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.Skill", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.SkillExpectation", "Expectations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SkillId");

                            b1.ToTable("SkillExpectations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.OwnsMany("GestionCapacidad.Domain.Entities.SkillLevelCriteria", "Levels", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Criteria")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.Property<int>("Level")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SkillId");

                            b1.ToTable("SkillLevelCriteria", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("Expectations");

                    b.Navigation("Levels");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.SprintSnapshot", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.ActivityDaySnapshot", "Activity", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Commits")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<int>("Features")
                                .HasColumnType("integer");

                            b1.Property<int>("Releases")
                                .HasColumnType("integer");

                            b1.Property<Guid>("SprintSnapshotId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SprintSnapshotId");

                            b1.ToTable("SprintSnapshotActivity", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SprintSnapshotId");
                        });

                    b.OwnsMany("GestionCapacidad.Domain.Entities.ConcurrentInitiativeSnapshot", "Initiatives", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("EpicId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("EpicTitle")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("InitiativeId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("InitiativeName")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<decimal>("Points")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("SprintSnapshotId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("SprintSnapshotId");

                            b1.ToTable("SprintSnapshotInitiatives", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SprintSnapshotId");
                        });

                    b.OwnsMany("GestionCapacidad.Domain.Entities.WorkItemSnapshot", "WorkItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("AddedAfterSprintStart")
                                .HasColumnType("boolean");

                            b1.Property<string>("Board")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("EpicId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("EpicTitle")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("InitiativeId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("InitiativeName")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("Number")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Points")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("SprintSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Tag")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("WorkItemId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("SprintSnapshotId");

                            b1.ToTable("SprintSnapshotWorkItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SprintSnapshotId");
                        });

                    b.Navigation("Activity");

                    b.Navigation("Initiatives");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("GestionCapacidad.Domain.Entities.TallaBandSet", b =>
                {
                    b.OwnsMany("GestionCapacidad.Domain.Entities.TallaBand", "Bands", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Lectura")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<decimal>("PmMax")
                                .HasColumnType("decimal(6,2)");

                            b1.Property<decimal>("PmMin")
                                .HasColumnType("decimal(6,2)");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Talla")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)");

                            b1.Property<Guid>("TallaBandSetId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TallaBandSetId");

                            b1.ToTable("TallaBands", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TallaBandSetId");
                        });

                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
